kajibi/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='accueil'),
    path('jeux/', views.jeux, name='jeux'),
    path('jeux/<int:page>/', views.jeux, name='jeux'),
    path('fiche/<int:game_id>/', views.fiche, name='fiche'),
    path('new_location/', views.new_location, name='new_location'),
    path('location/<int:location_id>/', views.location, name='location'),
    path('location/', views.location_list, name='location_list'),
    path('location/old/', views.old_location_list, name='old_location_list'),
    path('location/old/<int:page>/', views.old_location_list, name='old_location_list'),
    re_path(r'^game_autocomplete/$', views.GameAutocomplete.as_view(), name='game_autocomplete'),
    path('location/<int:location_id>/delete/', views.delete_location, name='delete_location'),
    path('location/<int:location_id>/finish/', views.finish_location, name='finish_location'),
    path('login/', views.connect, name='login'),
    path('logout/', views.deconnect, name='logout'),
]

pjeux_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kajibi/', include("kajibi.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kajibi/models.py
from django.db import models
import datetime
from django.utils import timezone

GUARANTEES = (
    ('ID', 'Carte d\'identité'),
    ('ACCESS', 'Carte d\'accès'),
    ('DRIVER', 'Permis de conduire'),
    ('KEY', 'Clés'),
    ('MONEY', 'Cash : voir le montant en commentaire)'),
    ('Autre', 'Autre : voir en commentaire')
)


class Game(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nom du jeux")
    players_min = models.IntegerField(verbose_name="Nombre de joueurs minimum")
    players_max = models.IntegerField(verbose_name="Nombre de joueurs maximum")
    duration_min = models.IntegerField(verbose_name="Durée minimum")
    duration_max = models.IntegerField(verbose_name="Durée maximum")
    picture = models.ImageField(upload_to="photos/", verbose_name="Photo du jeux", null=True, blank=True)
    nb_rented = models.IntegerField(verbose_name="Nombre de fois loué", default=0)
    description = models.TextField(verbose_name="Description du jeu")
    comments = models.TextField(verbose_name="Commentaires", null=True, blank=True)
    date = models.DateTimeField(default=timezone.now, verbose_name="Date d'ajout")
    is_rented = models.BooleanField(default=False, verbose_name="En cours de location", blank=True)

    def __str__(self):
        return self.name

    def duration(self):
        """Generate the duration string"""
        if self.duration_min == self.duration_max:
            return str(self.duration_min) + " minutes"
        else:
            return str(self.duration_min) + " à " + str(self.duration_max) + " minutes"

    def players(self):
        """Generate the number of players string"""
        if self.players_min == self.players_max:
            return str(self.players_min) + " joueurs"
        else:
            return str(self.players_min) + " à " + str(self.players_max) + " joueurs"

    class Meta:
        verbose_name = "Jeu"
        verbose_name_plural = "Jeux"


class Location(models.Model):
    date_begin = models.DateTimeField(default=timezone.now, verbose_name="Début de la location")
    expected_date_end = models.DateField(verbose_name="Fin prévue de la location")
    date_end = models.DateField(blank=True, null=True, verbose_name="Fin de la location")
    renter_first_name = models.CharField(max_length=20, verbose_name="Prénom du locataire")
    renter_last_name = models.CharField(max_length=20, verbose_name="Nom du locataire")
    renter_address = models.CharField(max_length=255, verbose_name="Adresse du locataire")
    renter_email = models.EmailField(verbose_name="E-mail du locataire")
    renter_phone = models.CharField(max_length=13, verbose_name="Numéro de téléphone du locataire")
    renter_guarantee = models.CharField(max_length=255, choices=GUARANTEES, verbose_name="Caution pour la location")
    renter_group = models.CharField(max_length=255, blank=True, null=True,
                                    verbose_name="Organisation du locataire (KAP, Cercle, Régio, etc.)")
    comments = models.TextField(blank=True, null=True, verbose_name="Commentaires")
    rented_games = models.ManyToManyField(Game, limit_choices_to={'is_rented': False})
    price = models.IntegerField(blank=True, null=True, verbose_name="Prix de la location")
    finished = models.BooleanField(default=False, verbose_name="Location finie")
    rentor_first = models.CharField(max_length=30, verbose_name="Reponsable sortie")
    rentor_last = models.CharField(max_length=30, verbose_name="Reponsable retour", null=True, blank=True)

    def finish(self):
        """Ends the location"""
        self.date_end = timezone.now()
        for game in self.rented_games.all():
            game.nb_rented += 1
            game.is_rented = False
            game.save()
        self.price = self.compute_price()
        self.finished = True
        self.save()

    def delete2(self):
        for game in self.rented_games.all():
            game.is_rented = False
            game.save()
        self.delete()

    def compute_price(self):
        """Computes the total price of the location, accounting for the number of games and the weekend"""
        # Removing the hours from the beginning and the end date (for example, a 23h rental should count as a full day)
        begin = datetime.date(self.date_begin.year, self.date_begin.month, self.date_begin.day)

        # Depending on whether the rental is late or not, and whether it is not over, we consider different end dates
        if self.finished:
            end = self.date_end
        elif not self.finished and self.is_late():
            end = datetime.date.today()
        elif not self.finished and not self.is_late():
            end = self.expected_date_end
        day = datetime.timedelta(days=1)
        price = 0
        i = 0
        while begin+i*day < end:
            price += self.rented_games.count()
            # The weekdays count as 1 day, whereas the week-end (friday->monday) counts as 1 day, so we skip it
            if 0 <= (begin+i*day).weekday() <= 3:
                i += 1
            elif (begin+i*day).weekday() == 4:
                i += 3
            elif (begin+i*day).weekday() == 5:
                i += 2
            else:
                i += 1
        return price

    def is_late(self):
        """Retourne vrai si la location est en retard (ou l'était si elle est finie)"""
        if self.finished:
            return self.expected_date_end < self.date_end
        else:
            return datetime.date.today() > self.expected_date_end

    def delay(self):
        """Retourne le nombre de jours de retard, 0 si pas de retard"""
        if not self.is_late:
            return 0
        else:
            if self.finished:
                return (self.date_end-self.expected_date_end).days
            else:
                return (datetime.date.today() - self.expected_date_end).days

    def number_of_games(self):
        """Retourne le nombre de jeux de cette location"""
        return self.rented_games.all().count()

    def __str__(self):
        return "Location n°" + str(self.id)

    class Meta:
        verbose_name = "Location"
        verbose_name_plural = "Locations"

kajibi/forms.py
from django.forms import ModelForm, TextInput, EmailInput, DateInput, Textarea
from .models import Location, Game
from django import forms
from dal import autocomplete
import datetime


class BootstrapModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BootstrapModelForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class LocationForm(BootstrapModelForm):
    class Meta:
        model = Location
        fields = ['renter_first_name', 'renter_last_name', 'renter_address', 'renter_phone', 'renter_email',
                  'renter_guarantee', 'renter_group', 'rented_games', 'expected_date_end', 'comments', 'rented_games']
        widgets = {
            'renter_first_name': TextInput(attrs={'placeholder': 'Prénom'}),
            'renter_last_name': TextInput(attrs={'placeholder': 'Nom'}),
            'renter_address': TextInput(attrs={'placeholder': '123 rue lambda'}),
            'renter_phone': TextInput(attrs={'placeholder': '0123456789'}),
            'renter_email': EmailInput(attrs={'placeholder': 'abc@xyz.com'}),
            'renter_group': TextInput(attrs={'placeholder': 'KAP, Cercle, Régio, ...'}),
            'expected_date_end': DateInput(attrs={'placeholder': '1 janvier 2020'}),
            'rented_games': autocomplete.ModelSelect2Multiple(url='game_autocomplete'),
            'comments': Textarea(attrs={'rows': 5})
        }

    def clean_expected_date_end(self):
        expected_date_end = self.cleaned_data['expected_date_end']
        if expected_date_end < datetime.date.today():
            raise forms.ValidationError("Veuillez saisir une date valide")
        else:
            return expected_date_end


class BootstrapLoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BootstrapLoginForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class LoginForm(BootstrapLoginForm):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Kajien'}))
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe'}))


class SearchForm(forms.Form):
    query = forms.CharField(label="Recherche", max_length=50)

kajibi/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from kajibi.models import Game, Location
from kajibi.forms import LocationForm, LoginForm, SearchForm

from dal import autocomplete


def home(request):
    """ Index page """
    return render(request, 'kajibi/accueil.html')


def jeux(request, page=1):
    """ Liste de tous les jeux"""
    all_games = Game.objects.order_by('-nb_rented')

    query = request.GET.get("q")
    if query:
        all_games = all_games.filter(name__icontains=query)

    paginator = Paginator(all_games, 5)
    try:
        games = paginator.page(page)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)

    return render(request, 'kajibi/jeux.html', {'games': games})


def fiche(request, game_id):
    """Affiche la fiche d'un jeu"""
    # TODO il faut gérer le cas où le jeu n'existe pas
    game = Game.objects.get(id=game_id)
    return render(request, 'kajibi/fiche.html', {'game': game})


@login_required
def new_location(request):
    """Nouvelle location"""
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            location_object = form.save()
            location_object.rentor_first = request.user.username
            messages.success(request, 'La location n°' + str(location_object.id) + ' a bien été créée !')
            for game in location_object.rented_games.all():
                game.is_rented = True
                game.save()
            return redirect('location', location_id=location_object.id)
    else:
        form = LocationForm()
    return render(request, 'kajibi/new_location.html', {'form': form})


class GameAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        # if not self.request.user.is_authenticated():
        #    return Game.objects.none()
        qs = Game.objects.filter(is_rented=False)
        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        return qs


@login_required
def location(request, location_id):
    """Affiche une location"""
    # TODO Gérer le cas où la location n'existe pas
    location_object = Location.objects.get(id=location_id)
    return render(request, "kajibi/location.html", {'location': location_object})


@login_required
def location_list(request):
    """Affiche toutes les locations en cours"""
    locations = Location.objects.order_by('-date_begin').filter(finished=False)
    return render(request, "kajibi/location_list.html", {'locations': locations})


@login_required
def old_location_list(request, page=1):
    """Affiche toutes les anciennes locations"""
    all_locations = Location.objects.order_by('-date_end').filter(finished=True)
    paginator = Paginator(all_locations, 20)

    try:
        locations = paginator.page(page)
    except EmptyPage:
        locations = paginator.page(paginator.num_pages)

    return render(request, "kajibi/old_location_list2.html", {'locations': locations})


@login_required
def delete_location(request, location_id):
    # TODO checker que user connecté
    location_object = get_object_or_404(Location, id=location_id)
    location_object.delete2()
    messages.success(request, "La location n°" + str(location_object.id) + " a bien été supprimée")
    return redirect('location_list')


@login_required
def finish_location(request, location_id):
    # TODO checker que user connecté
    location_object = get_object_or_404(Location, id=location_id)
    location_object.rentor_last = request.user.username
    location_object.finish()
    messages.success(request, "La location n°" + str(location_object.id) + " est bien finie")
    return redirect('location', location_id=location_id)


def connect(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                messages.success(request, "Bienvenue, " + username + " !")
                login(request, user)
                return redirect('accueil')
            else:
                messages.error(request, "Utilisateur ou mot de passe incorrect")
    else:
        form = LoginForm()
    return render(request, 'kajibi/login.html', {'form': form})


def deconnect(request):
    logout(request)
    return redirect('accueil')

kajibi/templates/kajibi/accueil.html
{% extends 'kajibi/base.html' %}

{% block content %}
<main role="main" class="container">

      <div class="starter-template">
        <h1>Bienvenue sur le site du KAJ</h1>
        <p class="lead">Viens louer des jeux<br>
            Ce sera sympa</p>
      </div>

    </main>
{%  endblock %}

kajibi/templates/kajibi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Kajibi</title>
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href=""{% static 'octicons/build/build.css' %}>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block style %}
    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">KAJ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'accueil' %}">Accueil<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jeux' %}">Nos jeux</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'location_list' %}">Locations en cours</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'new_location' %}">Nouvelle location</a>
                </li>
                {% endif %}
                <li>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="">
                        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Chercher un jeu" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">Chercher</button>
                    </form>
                </li>
            </ul>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <span class="navbar-text">{{ user.username }} - </span> <a class="nav-item nav-link " href="{% url 'logout' %}">Se déconnecter</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Se connecter</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">

    {% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
    <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>

{% endfor %}
        {% block content %}
        {% endblock %}
    </div>
{% block footer %}
    <div class="fixed-bottom"><p class="text-center small">By Rick - 2018</p></div>
{% endblock %}
</body>
</html>

kajibi/templates/kajibi/fiche.html
{% extends 'kajibi/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
    {% if game.is_rented %}
                <div class="alert alert-info" role="alert">
                    Ce jeu est actuellement loué
                </div>
            {% endif %}
        <div class="row">
            <h2 class="col-md-6">{{ game.name }}</h2>
            <div class="col-md-3">
                <img src="{% static 'octicons/build/svg/clock.svg' %}" /> &nbsp <span> {{ game.duration }}</span>
            </div>
            <div class="col-md-3">
                <img src="{% static 'octicons/build/svg/organization.svg' %}" /> &nbsp <span>{{ game.players }} </span>
            </div>
        </div>
        <div class="row">
            <article class="col-md-4"><img src="{{ game.picture.url }}" class="img-responsive" style="width: 100%"/></article>
            <article class="col-md-8" ><p class="lead">{{ game.description }}</p></article>
        </div>
    </div>
{% endblock %}

kajibi/templates/kajibi/jeux.html
{% extends 'kajibi/base.html' %}
{% load static %}
{% block style %}
{% endblock %}


{% block content %}
    <h1>Tous nos jeux</h1>
    <section class="col-xs-12 col-sm-6 col-md-12">
    {% for game in games %}
		<article class="search-result row">
			<div class="col-xs-12 col-sm-12 col-md-3">
				<a href="{% url 'fiche' game.id %}" class="thumbnail"><img src="{{ game.picture.url }}" height="120px" /></a>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-2">
				<ul class="meta-search"">
					<li><img src="{% static 'octicons/build/svg/clock.svg' %}" /> &nbsp <span> {{ game.duration }}</span></li>
					<li><img src="{% static 'octicons/build/svg/organization.svg' %}" /> &nbsp <span>{{ game.players }} </span></li>
                    {% if game.is_rented %}
                        <span class="badge badge-primary">Loué</span>
                    {% endif %}
				</ul>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-7 excerpet">
				<h3 class="text-uppercase"><a href="{% url 'fiche' game.id %}" title="">{{ game.name }}</a></h3>
				<p class="text-justify">{{ game.description|truncatechars:385 }}</p>
			</div>
			<span class="clearfix borda"></span>
		</article>

        {% empty %}
        <p>Aucun jeu.</p>
    {% endfor %}
    </section>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if games.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'jeux' games.previous_page_number %}">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Précédent</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Précédent</span>
                  </a>
                </li>
            {% endif %}

            {% for pagenum in games.paginator.page_range %}
                <li class="page-item {% if games.number == pagenum %} active{% endif %}">
                    <a class="page-link" href="{% url 'jeux' pagenum %}">{{ pagenum }}</a>
                </li>
            {% endfor %}

            {% if games.has_next %}
              <li class="page-item">
                  <a class="page-link" href="{% url 'jeux' games.next_page_number %}">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Suivant</span>
                  </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Suivant</span>
                  </a>
              </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

kajibi/templates/kajibi/location.html
{% extends 'kajibi/base.html' %}
{% load static %}

{% block content %}
    {% if location.finished == True %}
            <div class="alert alert-info" role="alert">
                Cette location est finie
            </div>
        {% elif location.is_late == True %}
            <div class="alert alert-warning" role="alert">
                Cette location a {{ location.delay }} jour{% if location.delay > 1 %}s{% endif %} de retard
            </div>
        {% endif %}
    <div class="container">
        <div class="row">
            <h1>{{ location }}</h1>
        </div>

        <div class="row">
            <div class="col-md-6">
                <ul style="padding-left: 0 !important; list-style: none; ">
                    <li>Loué par <strong>{{ location.renter_first_name }} {{ location.renter_last_name }}</strong>
                    {% if location.renter_group %} du {{ location.renter_group }} {% endif %}</li>
                    <li><img src="{% static 'octicons/build/svg/home.svg' %}" /> &nbsp <span> {{location.renter_address}}</span></li>
                    <li><img src="{% static 'octicons/build/svg/mail.svg' %}" /> &nbsp <span>{{location.renter_email}} </span></li>
                    <li><img src="{% static 'octicons/build/svg/device-mobile.svg' %}" /> &nbsp <span>{{location.renter_phone}} </span></li>
                    <li> Respo sortie : {{ location.rentor_first }}</li>
                    {% if location.rentor_last %} <li>Respo retour : {{ location.rentor_last }}</li>{% endif %}
                </ul>
            </div>
            <div class="col-md-6">
                Date de début : {{ location.date_begin.date }}<br />
                Date prévue de fin : {{ location.expected_date_end }}<br />
                {% if location.finished %} Date de fin : {{ location.date_end }} <br />
                Montant payé :
                {% else %} Montant à payer : {% endif %}
                {{ location.compute_price }}€
                {% if location.is_late == True %}
                    ({{ location.delay }} jour{% if location.delay > 1 %}s{% endif %} de retard)
                {% endif %}<br />
                Caution : {{ location.get_renter_guarantee_display }}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h3>Jeux loués</h3>
            </div>
            <div class="col-md-6">
                {% if location.comments %}<h3>Commentaires</h3>{% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    {% for game in location.rented_games.all %}
                        <a href="{% url 'fiche' game.id %}" class="list-group-item list-group-item-action">
                            {{ game.name }}
                        </a>
                    {% endfor %}
                </ul>
            <br />
            </div>
            <div class="col-md-6">
                {% if location.comments %}{{ location.comments }}{% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <button type="button" class="btn btn-primary btn-lg">Imprimer la facture</button>
            </div>
            {% if location.finished == False %}
                <div class="col-md-4">
                    <a href="{% url 'finish_location' location.id %}">
                        <button type="button" class="btn btn-success btn-lg" type="submit">Finir la location</button>
                    </a>
            </div>
            {% endif %}
            <div class="col-md-4">
                <a href="{% url 'delete_location' location.id %}">
                    <button type="submit" class="btn btn-danger btn-lg">Supprimer la location</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kajibi/templates/kajibi/location_list.html
{% extends 'kajibi/base.html' %}
{% load static %}

{% block style %}
<script type="text/javascript">
$(document).ready(function() {

    $('tr').click(function() {
        var href = $(this).find("a").attr("href");
        if(href) {
            window.location = href;
        }
    });

});
</script>
{% endblock %}

{% block content %}
    <h1>Locations en cours</h1>
    {{ location }}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Locataire</th>
                <th scope="col">Nombre de jeux</th>
                <th scope="col">A payer</th>
                <th scope="col">Date de retour</th>
            </tr>
        </thead>
        <tbody>
            {% for location in locations %}
                <tr class="{% if location.is_late %}table-warning{% endif %}">
                    <td scope="row"><a href="{% url 'location' location.id %}">{{ location.id }}</a></td>
                    <td>{{ location.renter_first_name }} {{ location.renter_last_name }} {% if location.renter_group %} du {{ location.renter_group }} {% endif %} </td>
                    <td>{{ location.number_of_games }}</td>
                    <td>{{ location.compute_price }} €</td>
                    <td>{% if location.is_late %}<strong>{% endif %}{{ location.expected_date_end }}{% if location.is_late %}</strong>{% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p class="text-center"><a href="{% url 'old_location_list' %}">Anciennes locations</a></p>
{% endblock %}

kajibi/templates/kajibi/login.html
{% extends 'kajibi/base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="alert alert-success" role="alert">
                Tu es déjà connecté, {{ user.username }} !
        </div>
    {% else %}

        <form class="form-signin" method="post" action=".">
        {% csrf_token %}
            {{ form.username.errors }}
            {{ form.password.errors }}
            {{ form.non_field_errors }}
        <h2 class="form-signin-heading">Se connecter</h2>
        <label for="{{ form.username.id_for_label }}" class="sr-only">Kajien</label>
        {{ form.username }}
        <label for="{{ form.username.id_for_label }}" class="sr-only">Mot de passe</label>
        {{ form.password }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Se connecter</button>
      </form>
    {% endif %}
{% endblock %}